# Generated by Django 3.1.5 on 2021-06-09 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=150, null=True)),
                ('post_id', models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True)),
                ('That', models.FileField(null=True, upload_to=main.models.upload_location_that)),
                ('That_text', models.CharField(max_length=150, null=True)),
                ('That_filetype', models.CharField(max_length=150, null=True)),
                ('That_fileSize', models.CharField(max_length=150, null=True)),
                ('That_fileExtension', models.CharField(max_length=150, null=True)),
                ('This', models.FileField(null=True, upload_to=main.models.upload_location_this)),
                ('This_text', models.CharField(max_length=150, null=True)),
                ('This_filetype', models.CharField(max_length=150, null=True)),
                ('This_fileSize', models.CharField(max_length=150, null=True)),
                ('This_fileExtension', models.CharField(max_length=150, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('Ip_address', models.CharField(blank=True, max_length=150, null=True)),
                ('user_city', models.CharField(blank=True, max_length=150, null=True)),
                ('user_country', models.CharField(blank=True, max_length=150, null=True)),
                ('user_browser', models.CharField(blank=True, max_length=150, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Voted_for', models.CharField(blank=True, max_length=4, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('Ip_address', models.CharField(blank=True, max_length=150, null=True)),
                ('user_city', models.CharField(blank=True, max_length=150, null=True)),
                ('user_country', models.CharField(blank=True, max_length=150, null=True)),
                ('user_browser', models.CharField(blank=True, max_length=150, null=True)),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.post')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(max_length=1550, null=True)),
                ('comment_id', models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True)),
                ('deleted', models.BooleanField(default=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('Ip_address', models.CharField(blank=True, max_length=150, null=True)),
                ('user_city', models.CharField(blank=True, max_length=150, null=True)),
                ('user_country', models.CharField(blank=True, max_length=150, null=True)),
                ('user_browser', models.CharField(blank=True, max_length=150, null=True)),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.post')),
                ('root_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.comment', verbose_name='Root_id')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
